spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goods
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update